# Generated by Django 2.1.7 on 2019-04-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190412_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userimage2',
            field=models.ImageField(default='default1.jpg', upload_to='postimage'),
        ),
        migrations.AddField(
            model_name='post',
            name='userimage3',
            field=models.ImageField(default='default1.jpg', upload_to='postimage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userimage',
            field=models.ImageField(default='default1.jpg', upload_to='postimage'),
        ),
    ]
