# Generated by Django 2.1.7 on 2019-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190412_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userimage',
            field=models.ImageField(default='default.jpg', upload_to='postimage'),
        ),
    ]
