# Generated by Django 2.1.7 on 2019-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190412_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Catagory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
