# Generated by Django 2.1.7 on 2019-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
