# Generated by Django 2.1.7 on 2019-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190415_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Catagory',
            field=models.CharField(blank=True, choices=[('Goat', 'Goat'), ('Cow', 'Cow'), ('Birds', 'Birds'), ('Fishes', 'Fishes'), ('Farm Equipments', 'Farm Equipments'), ('Vegetables', 'Vegetables'), ('Flowers', 'Flowers'), ('Others..', 'Others..')], max_length=100, null=True),
        ),
    ]
