# Generated by Django 2.1.7 on 2019-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190415_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sellorbuy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
