# Generated by Django 2.1.7 on 2019-04-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_sellorbuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sellorbuy',
            new_name='SellorBuy',
        ),
    ]
