# Generated by Django 2.1.7 on 2019-04-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190416_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='SellorBuy',
        ),
    ]
